SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `users` (
 `id` INT(11) NOT NULL,
`name` VARCHAR(150) NOT NULL,
`lastName` VARCHAR(150) NOT NULL,
`studentID` INT(7) default NULL,
`username` VARCHAR(15) NOT NULL,
`password` VARCHAR(150) NOT NULL,
`type` VARCHAR(10) NOT NULL,
`ans` VARCHAR(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `users`
    ADD PRIMARY KEY (`id`);


ALTER TABLE `users`
    MODIFY `id` INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
COMMIT;

